### ISSUE TITLE
[question] Upload to Big Query: Too many values in row starting at position: 0.

### ISSUE THREAD

**Issue by robinkeunen** [embulk/embulk-output-bigquery#72]
Hi all,

I'm trying to upload a csv from s3 to big query but I'm having trouble debugging the following error:
`[...] :message=>"Too many values in row starting at position: 0."` I created the table with a sample csv that I uploaded by hand to Big Query.

I first uploaded the data from postgresql to s3 using the following configuration file.

**From pg to s3**
```yml
in:
  type: postgresql
  host: {{ env.V3_HOST }}
  user: {{ env.V3_USER }}
  password: {{ env.V3_PASSWORD }}
  database: {{ env.V3_DATABASE }}
  table: orderitem
  where: id >= 5686672  # 2017-06-12

  fetch_rows: 20000
  incremental: true

out:
  type: s3
  bucket: {{ env.S3_DATALAKE_BUCKET }}
  access_key_id: {{ env.AWS_ACCESS_KEY_ID }}
  secret_access_key: {{ env.AWS_SECRET_ACCESS_KEY }}
  path_prefix: dbimport/{{ "now" | date: "%Y-%m-%d" }}/orderitem
  file_ext: .csv.gzip
  formatter:
    type: csv
  encoders:
    - type: gzip
```

Then I'm trying to transfer data from s3 to big query with the following configuration. It works fine when I'm using the `csv` parser  but I'm trying the `none` parser as recommended. 

**From s3 to bq**
```yaml
in:
  type: s3
  bucket: {{ env.S3_DATALAKE_BUCKET }}
  access_key_id: {{ env.AWS_ACCESS_KEY_ID }}
  secret_access_key: {{ env.AWS_SECRET_ACCESS_KEY }}
  path_prefix: dbimport/{{ "now" | date: "%Y-%m-%d" }}/orderitem
  incremental: true
  decoders:
    - type: gzip
  parser:
    type: none
    column_name: payload

out:
  type: bigquery
  auth_method: json_key
  json_keyfile: {{ env.gbq_keyfile }}
  project: poc-bigquery-xxxx

  dataset: dwh
  table: orderitem
  mode: replace
  payload_column: payload

  with_rehearsal: true
```

How can I debug this?

Thank you for your help!

PS: I'm new to embulk and big query (currently testing it versus redshift)

**Comment by sonots** [comment]
Please paste the bq table schema and some lines of the cvs file, too.

It looks the schema and csv file does not match.

**Comment by robinkeunen** [comment]
the schema

```json
[
  {
    "name": "id",
    "type": "INT64",
    "mode": "required"
  },
  {
    "name": "offer_id",
    "type": "INT64",
    "mode": "required"
  },
  {
    "name": "order_id",
    "type": "INT64",
    "mode": "required"
  },
  {
    "name": "quantity",
    "type": "INT64"
  },
  {
    "name": "unitprice",
    "type": "INT64"
  },
  {
    "name": "pricecurrency",
    "type": "STRING"
  },
  {
    "name": "total",
    "type": "INT64"
  },
  {
    "name": "type",
    "type": "STRING"
  },
  {
    "name": "delivered",
    "type": "BOOL"
  },
  {
    "name": "adjustmentstotal",
    "type": "INT64"
  },
  {
    "name": "canceled",
    "type": "BOOL"
  },
  {
    "name": "cancellationreason",
    "type": "STRING"
  },
  {
    "name": "vatamount",
    "type": "INT64"
  },
  {
    "name": "vatrate",
    "type": "FLOAT64"
  },
  {
    "name": "promisedquantity",
    "type": "INT64"
  },
  {
    "name": "promisedtotal",
    "type": "INT64"
  },
  {
    "name": "farm_id",
    "type": "INT64"
  },
  {
    "name": "updatedat",
    "type": "DATETIME"
  },
  {
    "name": "deliveredquantity",
    "type": "INT64"
  },
  {
    "name": "deliveredtotal",
    "type": "INT64"
  },
  {
    "name": "missingquantityreason",
    "type": "STRING"
  }
]
```

A few lines:
[orderitem.csv.zip](https://github.com/embulk/embulk-output-bigquery/files/1084855/orderitem.csv.zip)

ps: sorry for the late reply, I took a look WE.

**Comment by sonots** [comment]
The csv has a line of column names at the first line. You have to cut it.

**Comment by sonots** [comment]
If I were you, I may debug as followings:

1. Put `delete_from_local_when_job_end: false` to out_bq configuration
2. Find intermediate local files to be uploaded to bigquery
3. Look the file, and upload it into bigquery from bq web console manually.
4. Repair the file so that uploading succeeds
5. Repair embulk config file so that it succeeds

**Comment by robinkeunen** [comment]
## step 1
I added `header_line: false` to the **pg to s3**  output formatter. 

## step 2
Following your advice, I tried uploading from my local temporary files. I noticed that the `updatedat` field was in the wrong format (datetime instead of timestamp and wrong date formatting for bigquery).

I modified the **pg to s3**  output formatter to:
```yml
[...]
  formatter:
    type: csv
    header_line: false
    column_options:
      updatedat: {format: '%Y-%m-%d %H:%M:%S %:z'}
```

I did not change the *s3 to bq* configuration file. The upload still failed with the same error (`"Too many values in row starting at position: 0."`) but I could upload the temporary files manually with the cli `bq load`.

## step 3
I added the line
```yml
out:
  type: bigquery
  [...]
  schema_file: /[...]/orderitem_schema.json
```
Now it works! Thank you for your help, do you want me to modify the documentation to add
- debug hints (cf your last comments),
- a note about `schema_file` in the Formatter Performance Issue section?
