### ISSUE TITLE
Milliseconds part in timestamp is not accurate.

### ISSUE THREAD

**Issue by kmrshntr** [embulk/embulk-output-bigquery#76]
I tried this example.

https://github.com/embulk/embulk-output-bigquery/tree/v0.4.5#run-example

But,  the unexpected result came out as following:

![2018-04-03 11 00 00](https://user-images.githubusercontent.com/300862/38227037-3667f4b0-3737-11e8-80ae-bc03fd488a8f.png)

The milliseconds part of values in timestamp column in BQ are `.000` although the source timestamp column in [CSV]( https://github.com/embulk/embulk-output-bigquery/blob/master/example/example.csv) has microseconds part `.100000`.

This is my config.yml. I didn't change `in:` part of [the example.](https://github.com/embulk/embulk-output-bigquery/blob/master/example/config_replace.yml)
```
in:
  type: file
  path_prefix: example/example.csv
  parser:
    type: csv
    charset: UTF-8
    newline: CRLF
    null_string: 'NULL'
    skip_header_lines: 1
    comment_line_marker: '#'
    columns:
      - {name: date,        type: string}
      - {name: timestamp,   type: timestamp, format: "%Y-%m-%d %H:%M:%S.%N", timezone: "+09:00"}
      - {name: "null",      type: string}
      - {name: long,        type: long}
      - {name: string,      type: string}
      - {name: double,      type: double}
      - {name: boolean,     type: boolean}
out:
  type: bigquery
  mode: append
  auth_method: json_key
  json_keyfile: ****
  auto_create_table: true
  dataset: example_dataset
  table: example
```

### versions:
java: 1.8.0_162 ( oracle )
embulk: v0.9.4
bigquery plugin: v0.4.5
